project: 'mongodb-primer'
master_doc: 'index'
logo: ".static/logo-mongodb.png"
paths:
  static: ['source/.static']
theme:
  name: 'primer'
  project: 'primer'
  sitename: "MongoDB Primer"
  book_path_base: 'MongoDB-primer'
  repo: 'docs'
  jira: 'DOCS'
  nav_excluded:
    - '/indexes'
    - '/insert'
    - '/installation'
    - '/modify'
    - '/query'
sidebars:
  '**':
    - 'pagenav.html'
    - 'formats.html'
...
